import React, { useState, useEffect } from 'react'
import { Card, FormField, Loader } from '../components'

function Home() {
  const [loading, setLoading] = useState(false)
  const [allPosts, setAllPosts] = useState(null)
  const [searchText, setSearchText] = useState('')

  const RenderCards = ({ data, title }) => {
    if (data.length > 0) {
      return data.map((post) => <Card key={post._id} {...post} />)
    }

    return (
      <h2 className="mt-5 text-xl font-bold uppercase text-[#6469ff]">
        {title}
      </h2>
    )
  }

  return (
    <section className="mx-auto max-w-7xl">
      <h2 className="text-[28px] font-extrabold text-[#222328]">
        DALL-E Image Generator
      </h2>
      <p className="max-w-[300px] text-lg italic text-[#666e75] md:max-w-[900px]">
        Browse through a collection of imaginative and visually stunning images
        generated by DALL-E AI
      </p>

      <div className="mt-8">
        <FormField />
      </div>

      <div className="mt-6">
        {loading ? (
          <div className="flex items-center justify-center">
            <Loader />
          </div>
        ) : (
          <>
            {searchText && (
              <h2 className="mb-3 text-xl font-medium text-[#666e75]">
                Showing results for{' '}
                <span className="font-semibold italic text-[#222328]">
                  {searchText}
                </span>
              </h2>
            )}
            <div className="grid grid-cols-1 gap-3 md:grid-cols-3 lg:grid-cols-4">
              {searchText ? (
                <RenderCards data={[]} title="No results found" />
              ) : (
                <RenderCards data={[]} title="No posts found" />
              )}
            </div>
          </>
        )}
      </div>
    </section>
  )
}

export default Home
